### ISSUE TITLE
Custom CameraSource

### ISSUE THREAD

**Issue by ajhool** [etman55/FaceDetectionSampleApp#1]
Hi @etman55 , I saw your issue about using your own custom camera with google mobile vision, and I'm curious if you were successful? I'm reading through your code now to figure it out.

It looks like you are using the regular cameras on the phone to feed video into the google mobile vision API. Are you actually using a custom camera?

**Comment by etman55** [comment]
Hi @ajhool , what i meant by custom camera as google mobile vision actually using a "CameraSource" class for accessing the camera and what i want to do is to use my own camera instance as my app is working with color detection and face detection so i should use my own camera instance not really a custom camera and this repo is just a sample app to make the mobile vision api works with the camera 1 for android and yes it worked but my really work was in this repo: https://github.com/etman55/1Sheeld-Android-App/blob/development/oneSheeld/src/main/java/com/integreight/onesheeld/shields/controller/utils/CameraHeadService.java

**Comment by ajhool** [comment]
Ah, I see. Nice work, and thank you for the response

**Comment by etman55** [comment]
you welcome :)
